In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('allMascotData.csv')

In [4]:
active = df.loc[df['status'] == 'active']

In [5]:
indians_active = active[active['team_name'].str.contains("Indian", na=False)]
redskins_active = active[active['team_name'].str.contains("Redskin", na=False)]
warriors_active = active[active['team_name'].str.contains("Warriors", na=False)]
braves_active = active[active['team_name'].str.contains("Braves", na=False)]
blackhawks_active = active[active['team_name'].str.contains("Blackhawks", na=False)]
chiefs_active = active[active['team_name'].str.contains("Chiefs", na=False)]

In [6]:
active_controversy = pd.concat([indians_active, redskins_active, warriors_active, braves_active, blackhawks_active, chiefs_active])

In [7]:
active_controversy = active_controversy.drop(active_controversy.columns[0], axis=1)

In [8]:
active_controversy.to_csv('allActive_raw.csv')

In [45]:
defunct = df.loc[df['status'] == 'defunct']
defunct = defunct[defunct['tidbit'].notna()]
defunct_notes = defunct["tidbit"] != ""
defunct = defunct[defunct_notes]
defunct_noMoreInfo = defunct[~defunct["tidbit"].str.contains("See more information at", na=False)]
defunct_all = defunct_noMoreInfo[~defunct_noMoreInfo["tidbit"].str.contains("consolidated", na=False)]
indians_defunct = defunct_all[defunct_all['team_name'].str.contains("Indian", na=False)]
redskins_defunct = defunct_all[defunct_all['team_name'].str.contains("Redskin", na=False)]
warriors_defunct = defunct_all[defunct_all['team_name'].str.contains("Warriors", na=False)]
braves_defunct = defunct_all[defunct_all['team_name'].str.contains("Braves", na=False)]
blackhawks_defunct = defunct_all[defunct_all['team_name'].str.contains("Blackhawks", na=False)]
chiefs_defunct = defunct_all[defunct_all['team_name'].str.contains("Chiefs", na=False)]

In [46]:
changedNames

,Unnamed: 0,team_name,city,state,status,url,tidbit,lat,long
6,6,Acworth Indians,Acworth,Georgia,defunct,/teams/acworth-indians,NaN,34.065933,-84.676880
11,11,Afton Indians,Afton,New York,defunct,/teams/afton-indians,Renamed the Crimson Knights in 2001.,42.228136,-75.526572
25,25,Albion Indians,Albion,Washington,defunct,/teams/albion-indians,NaN,46.790997,-117.250453
35,35,Alpha Indians,Alpha,Iowa,defunct,/teams/alpha-indians,NaN,42.996643,-92.047671
43,43,Alvarado Indians,Alvarado,Minnesota,defunct,/teams/alvarado-indians-0,NaN,48.194148,-96.996181
...,...,...,...,...,...,...,...,...,...
1824,1824,Pontiac Central Chiefs,Pontiac,Michigan,defunct,/teams/pontiac-central-chiefs,NaN,42.638922,-83.291047
1906,1906,Ree Heights Chiefs,Ree Heights,South Dakota,defunct,/teams/ree-heights-chiefs,NaN,44.518594,-99.200106
2234,2234,Southwest Indian School Chiefs,Peoria,Arizona,defunct,/teams/southwest-indian-school-chiefs,NaN,33.580611,-112.237294
2308,2308,Storden-Jeffers Chiefs,Storden,Minnesota,defunct,/teams/storden-jeffers-chiefs,NaN,44.037736,-95.318331
2553,2553,Washita Heights Chiefs,Corn,Oklahoma,defunct,/teams/washita-heights-chiefs,NaN,35.378109,-98.782017

In [36]:
changedNames = pd.concat([indians_defunct, redskins_defunct, warriors_defunct, braves_defunct, blackhawks_defunct, chiefs_defunct])

In [38]:
changedNames.to_csv('allChanged.csv')